[project]
authors = ["caesarnine <<binalkp91@gmail.com>>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "agents"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.5,<4"
nodejs = ">=22.8.0,<23"
uvicorn = ">=0.30.6,<0.31"
anthropic = ">=0.34.2,<0.35"
openai = ">=1.45.0,<2"
sqlalchemy = ">=2.0.34,<3"
fastapi = ">=0.114.1,<0.115"
websockets = ">=13.0.1,<14"
ipykernel = ">=6.29.5,<7"
psycopg2 = ">=2.9.9,<3"
python-magic = ">=0.4.27,<0.5"

[pypi-dependencies]
lxml = ">=5.3.0, <6"
alembic = ">=1.13.3, <2"
pyjwt = ">=2.9.0, <3"
passlib = ">=1.7.4, <2"
anthropic = { version = "*", extras = ["bedrock"] }
websockets = "*"
botocore = ">=1.35.33, <2"
boto3 = ">=1.35.33, <2"
python-dotenv = ">=1.0.1, <2"
pypdf = ">=5.0.1, <6"
pydantic-xml = { version = ">=2.13.1, <3", extras = ["lxml"] }
xmltodict = ">=0.14.2, <0.15"
